apiVersion: apps/v1
kind: Deployment
metadata:
  name: lbm-slis-deployment
  labels:
    app: lbm-slis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lbm-slis
  template:
    metadata:
      labels:
        app: lbm-slis
    spec:
      containers:
      - name: lbm-slis-server
        image: gcr.io/stack-doctor/lbm-slis:latest
        ports:
        - containerPort: 8080
        env:
          # Define the environment variable
          - name: ERROR_RATE
            valueFrom:
              configMapKeyRef:
                name: error-rate
                key: ERROR_RATE