apiVersion: v1
kind: Service
metadata:
  name: opentelemetrycollector
spec:
  ports:
  - name: grpc-otlp
    port: 55681
    protocol: TCP
    targetPort: 55681
  selector:
    app.kubernetes.io/name: opentelemetrycollector
  type: ClusterIP